"""Broader, domain-anchored query waves for large cider corpus expansion."""

from __future__ import annotations

EXPANDED_THEME_QUERIES: dict[str, tuple[str, ...]] = {
    "biochimie": (
        '"apple juice" physicochemical composition',
        '"apple must" sugars organic acids',
        '"apple wine" fermentation kinetics',
        '"fermented apple beverage" metabolomics',
        '"cider fermentation" malic acid metabolism',
        '"apple juice" enzymatic browning chemistry',
        '"apple juice concentrate" chemical composition',
        '"cider" ethanol glycerol residual sugar',
        '"apple beverage" pH acidity stability',
        '"cider" redox potential sulfur dioxide',
        '"apple juice" minerals trace elements',
        '"apple must" nitrogen fermentation chemistry',
    ),
    "microbiologie": (
        '"apple juice" yeast fermentation',
        '"apple must" microbial ecology',
        '"apple wine" Saccharomyces fermentation',
        '"apple wine" non-Saccharomyces yeast',
        '"cider" lactic acid bacteria',
        '"cider" malolactic fermentation',
        '"apple juice" spoilage microorganisms',
        '"cider" microbial succession',
        '"fermented apple" starter culture',
        '"apple juice" Alicyclobacillus control',
        '"apple juice" patulin microbial control',
        '"cider fermentation" yeast biodiversity',
    ),
    "polyphenols": (
        '"apple juice" phenolic profile',
        '"apple juice" polyphenol oxidation',
        '"cider" procyanidins astringency',
        '"cider" tannin polymerization',
        '"apple must" phenolic compounds',
        '"apple juice" antioxidant processing',
        '"apple wine" polyphenols',
        '"cider" phenolic extraction pressing',
        '"apple juice" flavanols clarification',
        '"cider" polyphenol sensory',
        '"apple juice" browning polyphenol oxidase',
        '"calvados" phenolic compounds ageing',
    ),
    "proteines": (
        '"apple juice" protein haze',
        '"apple juice" proteins clarification',
        '"cider" yeast assimilable nitrogen',
        '"apple must" amino acids',
        '"apple juice" proteomics',
        '"cider" peptides fermentation',
        '"apple juice" protein fining',
        '"cider" nitrogen yeast nutrition',
        '"apple juice" haze formation protein',
        '"apple must" nitrogenous compounds',
        '"cider" hydrogen sulfide nitrogen',
        '"apple juice" protein filtration',
    ),
    "jus_pomme": (
        '"apple juice" pressing yield',
        '"apple juice" enzymatic clarification',
        '"apple juice" membrane filtration',
        '"apple juice" pasteurization quality',
        '"apple juice" high pressure processing',
        '"apple juice" pulsed electric field',
        '"apple juice" pectinase treatment',
        '"apple juice" turbidity stability',
        '"apple juice" aroma processing',
        '"apple juice concentrate" processing',
        '"apple must" clarification fermentation',
        '"cider apple" maturity juice composition',
    ),
    "calvados_eau_vie": (
        '"calvados" volatile composition',
        '"calvados" barrel maturation',
        '"calvados" distillation chemistry',
        '"apple brandy" volatile compounds',
        '"apple brandy" oak ageing',
        '"apple brandy" distillation methanol',
        '"cider brandy" sensory analysis',
        '"cider spirit" maturation',
        '"apple eau-de-vie" aroma',
        '"apple brandy" ester composition',
        '"calvados" wood extractives',
        '"cider distillate" chemical composition',
    ),
    "pommeau": (
        '"Pommeau de Normandie" composition',
        '"Pommeau de Normandie" polyphenols',
        '"Pommeau de Normandie" volatile compounds',
        '"Pommeau" sensory analysis',
        '"Pommeau" physicochemical properties',
        '"apple mistelle" composition',
        '"apple mistelle" fermentation',
        '"fortified apple wine" chemistry',
        '"fortified cider" maturation',
        '"apple juice" mutage brandy',
        '"Pommeau" turbidity stability',
        '"Pommeau" oak ageing',
    ),
    "aromes_procede": (
        '"cider" volatile aroma profile',
        '"cider" ester formation fermentation',
        '"cider" sensory quality processing',
        '"apple wine" aroma compounds',
        '"apple juice" volatile compounds processing',
        '"cider" fermentation temperature aroma',
        '"cider" inoculation sensory analysis',
        '"cider" ageing aroma',
        '"fermented apple beverage" flavor',
        '"hard cider" consumer sensory',
        '"cider" headspace GC-MS',
        '"apple must" aroma fermentation',
    ),
}


def _transpose_queries(
    themes: dict[str, tuple[str, ...]],
) -> tuple[dict[str, str], ...]:
    wave_counts = {len(queries) for queries in themes.values()}
    if len(wave_counts) != 1:
        raise ValueError("expanded harvest themes must define the same number of queries")
    wave_count = wave_counts.pop()
    return tuple(
        {theme: queries[index] for theme, queries in themes.items()} for index in range(wave_count)
    )


CIDER_EXPANDED_QUERY_WAVES = _transpose_queries(EXPANDED_THEME_QUERIES)


SPECIALIZED_THEME_QUERIES: dict[str, tuple[str, ...]] = {
    "biochimie": (
        '"apple juice" cultivar chemical composition',
        '"apple juice" storage physicochemical quality',
        '"cider" fermentation kinetics sugar consumption',
        '"apple wine" organic acid profile',
        '"apple must" enzymatic oxidation',
        '"cider" carbon dioxide dissolved oxygen',
        '"apple juice" rheological properties',
        '"fermented apple" chemical characterization',
    ),
    "microbiologie": (
        '"cider" indigenous yeast strains',
        '"apple juice" lactic fermentation',
        '"apple must" spontaneous fermentation',
        '"cider" Oenococcus oeni',
        '"apple wine" microbial community',
        '"apple juice" yeast inactivation processing',
        '"cider" Brettanomyces spoilage',
        '"fermented apple" probiotic culture',
    ),
    "polyphenols": (
        '"apple juice" cultivar phenolic composition',
        '"cloudy apple juice" polyphenols',
        '"clear apple juice" phenolic compounds',
        '"cider" tannin protein interaction',
        '"apple juice" storage phenolic stability',
        '"apple must" oxidation polyphenol oxidase',
        '"cider" colour phenolic composition',
        '"apple wine" antioxidant capacity phenolics',
    ),
    "proteines": (
        '"apple juice" amino acid profile',
        '"cider" amino acid metabolism',
        '"apple must" yeast available nitrogen',
        '"apple juice" protein precipitation',
        '"cider" protein stability clarification',
        '"apple juice" peptide composition',
        '"apple wine" nitrogen compounds',
        '"cider fermentation" nutrient supplementation',
    ),
    "jus_pomme": (
        '"cloudy apple juice" processing stability',
        '"apple juice" ultrasound processing',
        '"apple juice" cold plasma processing',
        '"apple juice" ohmic heating',
        '"apple juice" ultrafiltration clarification',
        '"apple juice" storage quality',
        '"apple juice" cultivar processing quality',
        '"apple must" pressing extraction yield',
    ),
    "calvados_eau_vie": (
        '"apple brandy" gas chromatography aroma',
        '"calvados" sensory profile',
        '"apple spirit" volatile composition',
        '"cider distillation" volatile compounds',
        '"apple brandy" maturation wood',
        '"calvados" ageing kinetics',
        '"apple distillate" methanol',
        '"apple brandy" quality characterization',
    ),
    "pommeau": (
        '"Pommeau" chemical composition',
        '"Pommeau" aroma profile',
        '"Pommeau" phenolic profile',
        '"Pommeau" maturation',
        '"apple mistelle" sensory',
        '"apple mistelle" volatile compounds',
        '"fortified apple beverage" composition',
        '"mutage" apple juice cider',
    ),
    "aromes_procede": (
        '"cider" aroma active compounds',
        '"cider" volatile esters yeast strain',
        '"apple wine" sensory evaluation',
        '"apple juice" aroma retention processing',
        '"cider" maturation volatile profile',
        '"cider" flavor chemistry',
        '"fermented apple" GC-MS aroma',
        '"hard cider" sensory descriptors',
    ),
}

CIDER_SPECIALIZED_QUERY_WAVES = _transpose_queries(SPECIALIZED_THEME_QUERIES)


MATERIAL_THEME_QUERIES: dict[str, tuple[str, ...]] = {
    "biochimie": (
        '"apple cultivar" sugar acid composition',
        '"apple fruit" biochemical composition',
        '"apple varieties" physicochemical properties',
        '"apple fruit" metabolomics',
        '"apple cultivar" organic acids sugars',
        '"apple fruit" maturity chemical composition',
        '"apple pomace" fermentation chemistry',
        '"apple pulp" pectin cell wall chemistry',
        '"apple fruit" storage metabolism',
        '"apple raw material" cider quality',
    ),
    "microbiologie": (
        '"apple fruit" surface microbiome',
        '"apple cultivar" indigenous yeast',
        '"apple pomace" microbial fermentation',
        '"apple fruit" spoilage fungi',
        '"apple pulp" lactic acid fermentation',
        '"apple fruit" microbial ecology',
        '"apple pomace" yeast fermentation',
        '"apple fruit" postharvest microbiota',
        '"apple processing by-product" microorganisms',
        '"apple raw material" cider microbiology',
    ),
    "polyphenols": (
        '"apple pomace" polyphenol extraction',
        '"apple peel" phenolic compounds',
        '"apple cultivar" polyphenol profile',
        '"apple fruit" procyanidins tannins',
        '"apple varieties" antioxidant phenolics',
        '"apple pulp" polyphenol oxidase',
        '"apple skin" flavonoids phenolic',
        '"apple pomace" tannins procyanidins',
        '"apple fruit" phenolic maturity',
        '"apple press cake" polyphenols',
    ),
    "proteines": (
        '"apple pomace" protein extraction',
        '"apple seed" proteins peptides',
        '"apple fruit" amino acid profile',
        '"apple cultivar" nitrogen composition',
        '"apple fruit" proteomics',
        '"apple pomace" amino acids',
        '"apple pulp" protein composition',
        '"apple processing by-product" peptides',
        '"apple fruit" nitrogen metabolism',
        '"apple raw material" protein cider',
    ),
    "jus_pomme": (
        '"apple pomace" pectin extraction processing',
        '"apple press cake" valorization processing',
        '"apple cultivar" juice yield pressing',
        '"apple pulp" juice processing',
        '"apple fruit" cell wall pressing',
        '"apple pomace" drying processing',
        '"apple processing by-product" composition',
        '"apple varieties" juice quality',
        '"apple raw material" juice extraction',
        '"apple pomace" enzymatic treatment',
    ),
    "calvados_eau_vie": (
        '"apple cultivar" brandy volatile compounds',
        '"apple fruit" spirit distillation',
        '"apple varieties" calvados quality',
        '"apple raw material" brandy aroma',
        '"apple pomace" distillation volatile',
        '"apple fruit" eau-de-vie composition',
        '"apple cultivar" distillate quality',
        '"apple pulp" spirit fermentation',
        '"apple brandy" raw material cultivar',
        '"calvados apple" cultivar composition',
    ),
    "pommeau": (
        '"apple cultivar" pommeau quality',
        '"apple must" fortified beverage composition',
        '"apple fruit" mistelle production',
        '"apple varieties" pommeau aroma',
        '"apple raw material" pommeau',
        '"apple must" mutage chemistry',
        '"apple cultivar" fortified cider',
        '"apple fruit" fortified wine sensory',
        '"pommeau" apple varieties',
        '"apple must" mistelle quality',
    ),
    "aromes_procede": (
        '"apple cultivar" volatile aroma profile',
        '"apple fruit" aroma precursors',
        '"apple varieties" sensory quality',
        '"apple fruit" volatile compounds storage',
        '"apple pulp" aroma compounds',
        '"apple peel" volatile profile',
        '"apple cultivar" ester precursors',
        '"apple pomace" volatile compounds',
        '"apple fruit" GC-MS aroma',
        '"apple raw material" cider sensory',
    ),
}

CIDER_MATERIAL_QUERY_WAVES = _transpose_queries(MATERIAL_THEME_QUERIES)


MICROBIOLOGY_THEME_QUERIES: dict[str, tuple[str, ...]] = {
    "biochimie": (
        '"cider fermentation" yeast sugar acid metabolism',
        '"cider fermentation" yeast assimilable nitrogen hydrogen sulfide',
        '"cider" malic acid metabolism lactic acid bacteria',
        '"apple juice" Penicillium patulin biosynthesis',
        '"cider" microbial transformation polyphenols',
        '"apple must" microbial metabolism organic acids',
        '"cider" yeast glycerol ethanol fermentation kinetics',
        '"apple juice" microbial degradation patulin',
        '"cider" bacterial metabolism exopolysaccharides',
        '"apple must" fungicide residues yeast fermentation',
    ),
    "microbiologie": (
        '"cider fermentation" microbial succession microbiota',
        '"cider" Saccharomyces non-Saccharomyces yeast ecology',
        '"cider" Oenococcus oeni malolactic fermentation',
        '"cider" lactic acid bacteria Lactiplantibacillus Pediococcus',
        '"cider" acetic acid bacteria Acetobacter Gluconobacter',
        '"cider" Brettanomyces Zygosaccharomyces spoilage yeast',
        '"apple juice" Alicyclobacillus acidoterrestris spoilage',
        '"cider apples" Penicillium expansum patulin microbiome',
        '"apple cider" phageome bacteriophage microbial community',
        '"apple juice" Escherichia coli Salmonella Listeria',
    ),
    "polyphenols": (
        '"cider" yeast polyphenol biotransformation',
        '"cider" lactic acid bacteria phenolic metabolism',
        '"apple juice" patulin polyphenol microbial stability',
        '"cider fermentation" tannins microbial ecology',
        '"apple must" polyphenol oxidation indigenous yeast',
        '"cider" Brettanomyces phenolic off-flavour',
        '"apple juice" antifungal phenolic compounds spoilage',
        '"cider" Oenococcus phenolic compounds',
        '"apple fruit" Penicillium phenolic defense',
        '"cider fermentation" procyanidins yeast strain',
    ),
    "proteines": (
        '"cider fermentation" yeast assimilable nitrogen YAN',
        '"apple juice" free amino nitrogen yeast',
        '"cider" amino acid metabolism Saccharomyces',
        '"cider fermentation" nitrogen limitation non-Saccharomyces',
        '"apple must" protein clarification microbial stability',
        '"cider" peptide metabolism lactic acid bacteria',
        '"apple juice" nitrogen supplementation fermentation microbiology',
        '"cider" amino acids Oenococcus malolactic',
        '"apple juice" fungal enzymes Penicillium',
        '"cider" yeast autolysis mannoproteins',
    ),
    "jus_pomme": (
        '"apple juice" spoilage microorganisms survey',
        '"apple juice" Alicyclobacillus guaiacol control',
        '"apple juice" Zygosaccharomyces spoilage control',
        '"apple juice" Penicillium expansum patulin contamination',
        '"apple juice" Escherichia coli O157:H7 inactivation',
        '"apple juice" Salmonella Listeria food safety',
        '"apple juice" microbial inactivation UV pulsed electric field',
        '"apple juice" pasteurization microbial shelf life',
        '"apple juice concentrate" molds yeasts bacteria',
        '"unpasteurized apple cider" foodborne outbreak pathogens',
    ),
    "calvados_eau_vie": (
        '"cider distillation" yeast volatile precursor',
        '"apple brandy" fermentation microbiota',
        '"calvados" cider yeast fermentation',
        '"apple distillate" microbial ethyl carbamate precursor',
        '"apple brandy" malolactic fermentation volatile',
        '"cider spirit" acetic acid bacteria',
        '"apple brandy" indigenous yeast aroma',
        '"cider distillation" microbial spoilage',
        '"apple must" yeast methanol apple brandy',
        '"calvados" fermentation bacteria aroma',
    ),
    "pommeau": (
        '"Pommeau" microbial stability',
        '"Pommeau" yeast bacteria spoilage',
        '"apple mistelle" microbiological stability',
        '"fortified apple beverage" spoilage yeast',
        '"Pommeau" filtration microbial control',
        '"apple must" mutage yeast stability',
        '"fortified cider" Brettanomyces spoilage',
        '"apple mistelle" lactic acid bacteria',
        '"Pommeau" microorganisms maturation',
        '"fortified apple juice" microbial shelf life',
    ),
    "aromes_procede": (
        '"cider" non-Saccharomyces yeast aroma volatile esters',
        '"cider" Saccharomyces strain aroma fermentation',
        '"cider" Oenococcus malolactic aroma',
        '"cider" lactic acid bacteria volatile compounds',
        '"cider" acetic acid bacteria volatile acidity spoilage',
        '"cider" Brettanomyces off-flavour phenols',
        '"cider fermentation" Hanseniaspora Metschnikowia aroma',
        '"cider" microbial terroir sensory quality',
        '"apple juice" Alicyclobacillus guaiacol off-flavour',
        '"cider" microbial succession aroma formation',
    ),
}

CIDER_MICROBIOLOGY_QUERY_WAVES = _transpose_queries(MICROBIOLOGY_THEME_QUERIES)
