"""Durable local job contracts and persistence."""

from app.jobs.background_handlers import CorpusIngestionHandler, LongSynthesisHandler
from app.jobs.chat_handler import ChatAnswerHandler, ChatbotAnswerer
from app.jobs.contracts import (
    ACTIVE_JOB_STATES,
    ALLOWED_JOB_TRANSITIONS,
    JOB_ERROR_DISPOSITIONS,
    JOB_RETRY_DELAYS,
    JOB_STEP_LABELS,
    JOB_STEP_ORDER,
    MAX_JOB_ATTEMPTS,
    RESERVED_FUTURE_JOB_TYPES,
    ChatAnswerPayload,
    CorpusIngestionPayload,
    JobErrorDisposition,
    JobErrorKind,
    JobPublic,
    JobPublicError,
    JobState,
    JobStep,
    JobType,
    LongSynthesisPayload,
    can_transition,
    retry_delay_after,
)
from app.jobs.repository import (
    MAX_ACTIVE_JOBS_PER_CONVERSATION,
    ActiveJobLimitError,
    EnqueuedChat,
    JobRecord,
    JobRepository,
    LeaseRecoverySummary,
)
from app.jobs.worker import (
    DurableJobWorker,
    JobCancelledError,
    JobHandler,
    JobHandlerRegistry,
    JobHandlerResult,
    JobLeaseLostError,
    JobProgressContext,
    UnknownJobTypeError,
)

__all__ = [
    "ALLOWED_JOB_TRANSITIONS",
    "ACTIVE_JOB_STATES",
    "MAX_ACTIVE_JOBS_PER_CONVERSATION",
    "JOB_ERROR_DISPOSITIONS",
    "JOB_RETRY_DELAYS",
    "JOB_STEP_LABELS",
    "JOB_STEP_ORDER",
    "MAX_JOB_ATTEMPTS",
    "RESERVED_FUTURE_JOB_TYPES",
    "ChatAnswerPayload",
    "ActiveJobLimitError",
    "ChatAnswerHandler",
    "ChatbotAnswerer",
    "LongSynthesisHandler",
    "LongSynthesisPayload",
    "CorpusIngestionHandler",
    "CorpusIngestionPayload",
    "JobErrorDisposition",
    "JobErrorKind",
    "JobPublic",
    "JobPublicError",
    "JobRepository",
    "JobRecord",
    "LeaseRecoverySummary",
    "DurableJobWorker",
    "EnqueuedChat",
    "JobCancelledError",
    "JobHandler",
    "JobHandlerRegistry",
    "JobHandlerResult",
    "JobLeaseLostError",
    "JobProgressContext",
    "UnknownJobTypeError",
    "JobState",
    "JobStep",
    "JobType",
    "can_transition",
    "retry_delay_after",
]
